# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Jinwoo Jeong
baseurl:        ""
url:            "http://williamjeong2.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Jinwoo Jeong
  url:          http://williamjeong2.github.io
  email:        wjd5480@gmail.com
  github:       WilliamJeong2
  #twitter:      playpingpong

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/WilliamJeong2/WilliamJeong2.github.io
